# Generated by Django 4.0.2 on 2022-02-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nums',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nums',
            name='is_offer',
            field=models.BooleanField(null=True),
        ),
    ]
