# Generated by Django 4.0.2 on 2022-02-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_nums_age_nums_is_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nums',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
    ]
