# Generated by Django 4.0.2 on 2022-02-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_nums2'),
    ]

    operations = [
        migrations.CreateModel(
            name='nums3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('is_offer', models.BooleanField(default=False)),
                ('Foreignkey', models.ManyToManyField(to='app1.nums')),
            ],
        ),
    ]
